name: Lint Publish

on:
  push:
    branches: [main]

env:
  REPO_NAME: clamav-java
  JAVA_VERSION: 17.0.8
  JAVA_DISTRIBUTION: temurin

jobs:
  # linting and unit testing is not ready yet.
  publish:
    #needs: [unit-test]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{env.JAVA_VERSION}}
          distribution: ${{env.JAVA_DISTRIBUTION}}
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@8d49e559aae34d3e0eb16cde532684bc9702762b
      - name: Publish package
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:
          arguments: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_PUBLISH_PACKAGE }}
          GITHUB_ACTOR: ${{ secrets.GH_ACTOR_PUBLISH_PACKAGE }}